global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using NorthWind.EFCore.Repositories.DataContexts;
global using NorthWind.EFCore.Repositories.Respositories;
global using NorthWind.Sale.BusinessObjects.Interfaces.Repositories;
global using NorthWind.Sale.Controllers;
global using NorthWind.Sale.Presenters;
global using NorthWind.Sale.UseCases;